GET http://localhost:3000/view-balance/EFxUfYTLrFui9hz9Gx26jVSf45J7Y3dVj6y2T37Nj682



###
POST http://localhost:3000/create-account
Content-Type: application/json

{
  "keypair": {
    "publicKey": "9pyjdGYKhP3pFikhrENq9FXZft38bG3durcnML1V9njw",
    "privateKey": "4CkvZhxpoCKFmXShGg5MEgmZBgxmTn3qKQ37iubp2xgaU9DxwfXKK17TpTmD2tNWf7rP2xdpv5QTb1Z22jtfHVs3"
  },
  "initialBalance": 1000
}

###
POST http://localhost:3000/sign
Content-Type: application/json

{
  "message": "message",
  "privateKey": "4CkvZhxpoCKFmXShGg5MEgmZBgxmTn3qKQ37iubp2xgaU9DxwfXKK17TpTmD2tNWf7rP2xdpv5QTb1Z22jtfHVs3"
}

###
POST http://localhost:3000/verify
Content-Type: application/json

{
  "message": "message",
  "signature": "3Y5LLvvc1fhMpB7GKFYrzqmfXJD2rt2oLTTDgbmHtWfALGHK5oXGUterWnyXCfgPC3zvMXsUmzuV8MBPtJA4qgx4",
  "publicKey": "9pyjdGYKhP3pFikhrENq9FXZft38bG3durcnML1V9njw"
}



###
POST http://localhost:3000/create-account
Content-Type: application/json

{
  "keypair": {
    "publicKey": "EFxUfYTLrFui9hz9Gx26jVSf45J7Y3dVj6y2T37Nj682",
    "privateKey": "2QhFa2Eh9XrN322Y5tJRbZeGJkA6pEq6auXf7Uhs9c5Hp6UosdmmsMDcKWKsKQ5pUU1y3RJraAuQMCnxPtBjXvH8"
  },
  "initialBalance": 1000
}

###
//Transfer
POST http://localhost:3000/transfer
Content-Type: application/json

{
  "senderPublicKey": "3TtoDJxVc1nBvebboEgcGffQnJyVGXd4JsvHZr9YnVkw",
  "receiverPublicKey": "EFxUfYTLrFui9hz9Gx26jVSf45J7Y3dVj6y2T37Nj682",
  "amount": 100
}


